services:
  ehrbase-db:
    image: ehrbase/ehrbase-postgres:latest
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      EHRBASE_USER: ehrbase
      EHRBASE_PASSWORD: ehrbase
  ehrbase:
    image: ehrbase/ehrbase:next
    ports:
      - 8080:8080
    environment:
      DB_URL: jdbc:postgresql://ehrbase-db:5432/ehrbase
      DB_USER: ehrbase
      DB_PASS: ehrbase
      SYSTEM_NAME: local.ehrbase.org
